name: Publish a release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git credentials
        run: ./.github/bin/set-credentials

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "1.2.6"

      - name: Install Nim build tools
        run: ./.github/bin/install-build-tools

      - name: Check if there was a code change
        run: |
          if git diff --name-only ${{ github.event.before }} "${GITHUB_SHA}" | grep '^src/.*.nim$'; then
            echo 'NIMFILECHANGED=true' >> "${GITHUB_ENV}"
          fi

      - name: Bump version and push tag
        if:  env.NIMFILECHANGED == 'true'
        run: ./.github/bin/release

      - name: Build binary
        run: ./.github/bin/build

      - name: Export current version
        if:  env.NIMFILECHANGED == 'true'
        run: ./.github/bin/export-version

      - name: Publish release
        if:  env.NIMFILECHANGED == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tooling_webserver
          asset_name: tooling_webserver
          tag: ${{ env.VERSION }}
          overwrite: true
