name: Publish a release
on:
  push:
    branches:
      - master
    paths:
      - "**.nim"

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git credentials
        run: ./.github/bin/set-credentials

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "1.4.0"

      - name: Install Nim build tools
        run: ./.github/bin/install-build-tools

      - name: Bump version and push tag
        run: ./.github/bin/release

      - name: Build binary
        run: ./.github/bin/build

      - name: Export current version
        run: ./.github/bin/export-version

      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tooling_webserver
          asset_name: tooling_webserver
          tag: ${{ env.VERSION }}
          overwrite: false
